print("*-------------------------------------------*")
print()
print("Input First Name: ", end="")
Fname = str(input())
print("Input Middle Name: ", end="")
Mname = str(input())
print("Input Last Name: ", end="")
Lname = str(input())
print()
print("*-------------------------------------------*")
print()
Full_Name = Fname + " " + Mname + " " + Lname
print("Full Name:", Full_Name)
print()
print("*-------------------------------------------*")